### ISSUE TITLE
Ability to trigger Jmeter tests from API

### ISSUE THREAD

**Issue by kennethfl** [awslabs/distributed-load-testing-on-aws#21]
@beomseoklee I saw your answer regarding uploading zip files to include CSV configurations in an upcoming release. Would it also be possible to point the dlts to a zip in S3? I am currently kicking off `simple` tests from Jenkins via cURL. When I take a look at the json test scenario when I kick off a Jmeter load test from UI I see: {"script":"***.jmx"}  Is it possible to do the following :

```
curl --location --request POST 'https://****.us-east-1.amazonaws.com/prod/scenarios' \
                       --header 'Content-Type: text/plain' \
                       --data-raw '{
                           "testDescription": "'"$TEST_DESCRIPTION"'",
                           "testName": "'"$TEST_NAME"'",
                           "testType": "'"$TEST_TYPE"'",
                           "taskCount": "'"$TASK_COUNT"'",
                           "testScenario": {
                               "execution": [
                                   {
                                       "concurrency": "'"$CONCURRENT_USERS"'",
                                       "ramp-up": "'"$RAMP_UP_TIME"''"$RAMP_UP_TIME_UNIT"'",
                                       "hold-for": "'"$HOLD_CONCURRENCY_TIME"''"$HOLD_CONCURRENCY_TIME_UNIT"'",
                                       "scenario": "'"$TEST_NAME"'"
                                   }
                               ],
                               "scenarios": {
                                   "'"$TEST_NAME"'": {
                                       "script": "Jmeter-scripts/***.jmx"
                                   }
                               }
                           }
                       }'
```
I tried the above and I am able to trigger a test but it fails on parsing empty array 
```
2020-10-26T19:23:28.063Z	362131ee-2f7c-45cd-987e-830a20c2d552	ERROR	TypeError: Reduce of empty array with no initial value
    at Array.reduce (<anonymous>)
    at Object.finalResults (/var/task/lib/parser/index.js:178:50)
    at Runtime.exports.handler (/var/task/index.js:37:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
When I run the same script via UI it works.

**Comment by beomseoklee** [comment]
@kennethfl Thanks for contacting us. The way how it works is it downloads the `jmx` file from S3 bucket, and run the script file on AWS Fargate tasks. To do that, you need to upload your script file to the S3 bucket firstly so AWS Fargate tasks can download the script file (e.g. YOUR_SCENARIOS_BUCKET/public/test-scenarios/jmeter/$TEST_ID.jmx). Then, you may run the below curl command:

```
$ TEST_ID=`uuidgen`
$ curl --location --request POST 'https://****.us-east-1.amazonaws.com/prod/scenarios' \
                       --header 'Content-Type: text/plain' \
                       --data-raw '{
                           "testDescription": "'"$TEST_DESCRIPTION"'",
                           "testName": "'"$TEST_NAME"'",
                           "testType": "'"$TEST_TYPE"'",
                           "taskCount": "'"$TASK_COUNT"'",
                           "testScenario": {
                               "execution": [
                                   {
                                       "concurrency": "'"$CONCURRENT_USERS"'",
                                       "ramp-up": "'"$RAMP_UP_TIME"''"$RAMP_UP_TIME_UNIT"'",
                                       "hold-for": "'"$HOLD_CONCURRENCY_TIME"''"$HOLD_CONCURRENCY_TIME_UNIT"'",
                                       "scenario": "'"$TEST_NAME"'"
                                   }
                               ],
                               "scenarios": {
                                   "'"$TEST_NAME"'": {
                                       "script": "$TEST_ID.jmx"
                                   }
                               }
                           }
                       }'
```

Before running the command, please make sure you are authorized to execute the API Gateway by providing `authorization` and `x-amz-secuirty-token` headers.
